//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CropCanvas.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CropCanvas.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI:.
        /// </summary>
        public static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI + Crop.
        /// </summary>
        public static string AICrop {
            get {
                return ResourceManager.GetString("AICrop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string AILabel {
            get {
                return ResourceManager.GetString("AILabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI Outpainting.
        /// </summary>
        public static string AIOutpainting {
            get {
                return ResourceManager.GetString("AIOutpainting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected to ComfyUI - waiting for processing....
        /// </summary>
        public static string ComfyConnected {
            get {
                return ResourceManager.GetString("ComfyConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComfyUI error: {0}.
        /// </summary>
        public static string ComfyError {
            get {
                return ResourceManager.GetString("ComfyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating... step {0}/{1} ({2}%).
        /// </summary>
        public static string ComfyGenerating {
            get {
                return ResourceManager.GetString("ComfyGenerating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading model....
        /// </summary>
        public static string ComfyModelLoading {
            get {
                return ResourceManager.GetString("ComfyModelLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing workflow....
        /// </summary>
        public static string ComfyPreparing {
            get {
                return ResourceManager.GetString("ComfyPreparing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing done - fetching result....
        /// </summary>
        public static string ComfyProcessingDone {
            get {
                return ResourceManager.GetString("ComfyProcessingDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result downloaded!.
        /// </summary>
        public static string ComfyResultDownloaded {
            get {
                return ResourceManager.GetString("ComfyResultDownloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve result from ComfyUI history..
        /// </summary>
        public static string ComfyResultFailed {
            get {
                return ResourceManager.GetString("ComfyResultFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComfyUI outpainting took too long (timeout after 3 minutes)..
        /// </summary>
        public static string ComfyTimeout {
            get {
                return ResourceManager.GetString("ComfyTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebSocket unavailable - polling....
        /// </summary>
        public static string ComfyWsFallback {
            get {
                return ResourceManager.GetString("ComfyWsFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the folder with images.
        /// </summary>
        public static string DialogSelectImages {
            get {
                return ResourceManager.GetString("DialogSelectImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the output folder for cropped images.
        /// </summary>
        public static string DialogSelectOutput {
            get {
                return ResourceManager.GetString("DialogSelectOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ratio:.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select output folder.
        /// </summary>
        public static string SelectOutputFolder {
            get {
                return ResourceManager.GetString("SelectOutputFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select source folder.
        /// </summary>
        public static string SelectSourceFolder {
            get {
                return ResourceManager.GetString("SelectSourceFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading result....
        /// </summary>
        public static string StabilityDownloading {
            get {
                return ResourceManager.GetString("StabilityDownloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stability AI outpainting done!.
        /// </summary>
        public static string StabilityDone {
            get {
                return ResourceManager.GetString("StabilityDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stability AI error ({0}): {1}.
        /// </summary>
        public static string StabilityError {
            get {
                return ResourceManager.GetString("StabilityError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stability AI API key is not set..
        /// </summary>
        public static string StabilityNoKey {
            get {
                return ResourceManager.GetString("StabilityNoKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one direction must be > 0..
        /// </summary>
        public static string StabilityNoPadding {
            get {
                return ResourceManager.GetString("StabilityNoPadding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outpainting in progress via Stability AI....
        /// </summary>
        public static string StabilityProcessing {
            get {
                return ResourceManager.GetString("StabilityProcessing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ratio {0:F1}:1 too wide - adding {1}px vertical padding for Stability AI limit..
        /// </summary>
        public static string StabilityRatioWide {
            get {
                return ResourceManager.GetString("StabilityRatioWide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scaling image ({0:P0}) to fit Stability AI limits....
        /// </summary>
        public static string StabilityScaling {
            get {
                return ResourceManager.GetString("StabilityScaling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending to Stability AI (L:{0} U:{1} R:{2} D:{3})....
        /// </summary>
        public static string StabilitySending {
            get {
                return ResourceManager.GetString("StabilitySending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI padding: L:{0} U:{1} R:{2} D:{3}.
        /// </summary>
        public static string StatusAIPadding {
            get {
                return ResourceManager.GetString("StatusAIPadding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComfyUI not reachable at 127.0.0.1:8188 - start ComfyUI first..
        /// </summary>
        public static string StatusComfyNotFound {
            get {
                return ResourceManager.GetString("StatusComfyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to ComfyUI....
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cropping visible area....
        /// </summary>
        public static string StatusCropping {
            get {
                return ResourceManager.GetString("StatusCropping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a Stability AI API key first..
        /// </summary>
        public static string StatusEnterApiKey {
            get {
                return ResourceManager.GetString("StatusEnterApiKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Original: {0}x{1} | Crop: {2}x{3} | Ratio: {4}:{5}.
        /// </summary>
        public static string StatusFormat {
            get {
                return ResourceManager.GetString("StatusFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} images found.
        /// </summary>
        public static string StatusImagesFound {
            get {
                return ResourceManager.GetString("StatusImagesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}.
        /// </summary>
        public static string StatusLoadError {
            get {
                return ResourceManager.GetString("StatusLoadError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading images....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No image selected.
        /// </summary>
        public static string StatusNoImage {
            get {
                return ResourceManager.GetString("StatusNoImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No model found. Download an inpainting model (e.g. sd-v1-5-inpainting)..
        /// </summary>
        public static string StatusNoModel {
            get {
                return ResourceManager.GetString("StatusNoModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No extension needed - selection is within the image..
        /// </summary>
        public static string StatusNoPadding {
            get {
                return ResourceManager.GetString("StatusNoPadding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outpainting done! New size: {0}x{1} - you can now crop..
        /// </summary>
        public static string StatusOutpaintDone {
            get {
                return ResourceManager.GetString("StatusOutpaintDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outpainting error: {0}.
        /// </summary>
        public static string StatusOutpaintError {
            get {
                return ResourceManager.GetString("StatusOutpaintError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outpainting (L:{0} T:{1} R:{2} B:{3})....
        /// </summary>
        public static string StatusOutpainting {
            get {
                return ResourceManager.GetString("StatusOutpainting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading result....
        /// </summary>
        public static string StatusResultLoading {
            get {
                return ResourceManager.GetString("StatusResultLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved: {0} ({1}x{2}).
        /// </summary>
        public static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error saving: {0}.
        /// </summary>
        public static string StatusSaveError {
            get {
                return ResourceManager.GetString("StatusSaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a source folder to begin.
        /// </summary>
        public static string StatusSelectFolder {
            get {
                return ResourceManager.GetString("StatusSelectFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an image.
        /// </summary>
        public static string StatusSelectImage {
            get {
                return ResourceManager.GetString("StatusSelectImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uploading to ComfyUI....
        /// </summary>
        public static string StatusUploading {
            get {
                return ResourceManager.GetString("StatusUploading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ratio too tall - adding {0}px horizontal padding..
        /// </summary>
        public static string StabilityRatioTall {
            get {
                return ResourceManager.GetString("StabilityRatioTall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scaled: {0}x{1} + padding L:{2} U:{3} R:{4} D:{5}.
        /// </summary>
        public static string StabilityScaled {
            get {
                return ResourceManager.GetString("StabilityScaled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outpainting in progress... ({0}s).
        /// </summary>
        public static string ComfyPollProgress {
            get {
                return ResourceManager.GetString("ComfyPollProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComfyUI outpainting took too long (timeout after 2 minutes)..
        /// </summary>
        public static string ComfyPollTimeout {
            get {
                return ResourceManager.GetString("ComfyPollTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WebSocket error - polling as fallback....
        /// </summary>
        public static string ComfyWsError {
            get {
                return ResourceManager.GetString("ComfyWsError", resourceCulture);
            }
        }
    }
}
